### ISSUE TITLE
Crash in demo project

### ISSUE THREAD

**Issue by totoroyyb** [TastesLikeTurkey/Papyrus#5]
Hi there,
I've tried the demo project under the solution but something went wrong.
I loaded two books and clicked the menu, the compiler always  broke in this line
`await Parchment.LoadContentAsync(e.AddedItems.FirstOrDefault() as NavPoint);`, which is located in file `TableOfContents.xaml.cs` , line 69, with the exception of `System.IO.FileNotFoundException`

Having no idea what's going on, please check it out.
Any help are appreciated!

**Comment by ShawnTheBeachy** [comment]
I should be able to take a look at it this evening. Could you link to the books you're trying? ePub is an incredibly versatile format, and I'm guessing there's something different about the specific books you're trying.

**Comment by totoroyyb** [comment]
[Ebook.zip](https://github.com/TastesLikeTurkey/Papyrus/files/2172902/Ebook.zip)
Here are two books I've tried.
Thanks for your help!

**Comment by ShawnTheBeachy** [comment]
@totoroyyb Thanks for bringing this up! Apparently it's "valid" for an eBook to reference a file that does not exist. I've updated Papyrus to handle that. It looks like there's still an issue where the last line of a chapter is shown on the next chapter's page, but I'm not sure if that's specific to your eBooks or if it's just a general issue, and it's not really related to this issue anyway, so I'm closing this and I'll take a look at the last line duplication separately.

**Comment by totoroyyb** [comment]
@TastesLikeTurkey Thanks for checking out, glad to here it's fixed
