### ISSUE TITLE
Another issue around mimetype

### ISSUE THREAD

**Issue by totoroyyb** [TastesLikeTurkey/Papyrus#6]
Hi, me again.
I run over another issue with `Invalid minetype exception` when I was trying to open this book.
I check out this epub bundle and the minetype file do exist but I'm not sure what's going on

Thanks anyway!
[Hamilton, Alexander & Madison, James & Jay, John - The Federalist Papers (1943, Knowledge Products).zip](https://github.com/TastesLikeTurkey/Papyrus/files/2173688/Hamilton.Alexander.Madison.James.Jay.John.-.The.Federalist.Papers.1943.Knowledge.Products.zip)

**Comment by ShawnTheBeachy** [comment]
Thanks once again. This has been fixed.
